### ISSUE TITLE
مشکل در درک مستندات

### ISSUE THREAD

**Issue by ZarchiMohammad** [MrMahdi313/GapBot#2]
در قسمتی از مستندات بات های گپ نوشته شده : "توکن بات را در header با متد post ارسال کنید!" ، باید دقیقا چگونه عمل کرد برای فرستادن پیام به کاربر با فرض اینکه باتمون هم تعاملی باشه؟!

**Comment by mahdizojaji** [comment]
سلام و خسته نباشید
مستندات گپ برای زمانی هست که شما بخواید خودتون رکوئست بفرستید.
که باید توکن رو همراه هدر ارسال کنید.
اگر از این کتابخونه استفاده کنید فقط کافیه توکن رو به عنوان پارامتر به کلاس گپ بدید.
در رابطه با سوال دومتون هم عرض کنم درصورتی که قرار باشه بات از هر متدی استفاده کنه وارد کردن توکن اجباری هست.
فقط در صورتی نیاز به توکن نیست که فقط بخواید اپدیت هارو دریافت کنید.
همچنین توصیه میکنم برای اشنا شدن با کتابخونه حتما مثال هارو نگاه کنید:
https://github.com/MrMahdi313/GapBot/examples
اگر باز هم سوالی در این مورد بود در ادامه کامنت ها درخدمتتون هستم ولی در صورتی که جواب سوالتون رو گرفتید لطفا ابن Issue رو ببندید
