### ISSUE TITLE
سرور یا هاست برای ربات

### ISSUE THREAD

**Issue by Mahdiali313** [MrMahdi313/GapBot#7]
سلام دوستان.شما از چه سرور یا هاستی برای اجرای رباتتون استفاده میکنید؟
تریجیحا ارزان باشه .اگر در خارج از کشور باشه بهتر هم هست
میدونید که ربات ها رم و فضای زیادی لازم ندارن و اغلب سرویس دهنده ها سرورهای قوی ارزه میکنند که برای کارما لازم نیست والکی باید پول زیاد بدیم
 
این سرور های رایگان مثل این دو تا سایت زیر رو تست کردم.غیر از اینا اگر میدونید ممنون میشم بگید
https://www.heroku.com/
pythonanywhere.com

**Comment by mahdizojaji** [comment]
سلام و خسته نباشید
این سوالتون مربوط به این ریپازیتوری نیست.
