### ISSUE TITLE
small mistack in example

### ISSUE THREAD

**Issue by Mahdiali313** [MrMahdi313/GapBot#8]
Hello
the correct form of this line is:
https://github.com/Py-GapBot/GapBot/blob/0eba11bf63aa03f08399b7c4d100a82a77113eb9/examples/echo.py#L9
`if update['type'] == ['text']:`

thanks a lot for publish this library

**Comment by mahdizojaji** [comment]
سلام 
مشکل توی مثال ها هست ولی مشکلی که شما گفتید نیست.
نوع پیام یا همون کلید 
type 
از اپدیت که دریافت میکنید یک استرینگ هست و یک پیام همزمان نمیتونه چند نوع داشته باشه و مثال لیست که زدید اشتباه هست.
